version: '3.7'

services:
  database:
    image: mysql:5.7
    platform: linux/x86_64
    ports:
      - 3306:3306
    env_file:
      - mysql-settings.env
    volumes:
      - ${PWD}/db:/docker-entrypoint-initdb.d # Initalize an SQL file on startup - Could be removed after first run
      - database_volume:/var/lib/mysql
    restart: always

  # Could be excluded, but is a nice to have in dev-env
  adminer:
    image: adminer
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - database

  server:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/frontend:/frontend
      - ${PWD}/api:/api
    depends_on:
      - php

  php:
    build: ${PWD}/api/
    volumes:
      - ${PWD}/api:/api
    env_file:
      - php-db-con.env
    depends_on:
      - database

volumes:
  database_volume:
